### ISSUE TITLE
Device Token Issue

### ISSUE THREAD

**Issue by faizanShoukat55** [pushy/pushy-sdk-ios#14]
Hy Pushy 
My Flutter app is working perfectly. As I am getting the device token even the notification permission is denied. While in IOS native device token is null. That's why I am forcing users to allow notification permissions always otherwise you can't log in.
My question is is there any way to get the device token without giving permissions?

**Comment by pushy** [comment]
Hi @faizanShoukat55,
Thanks for reaching out. We'd be glad to assist.

We apologize for this inconsistent behavior between the iOS and Android SDKs. Indeed, on Android, the Pushy SDK will still return a device token even if the user has not yet consented to receiving notifications, whereas on iOS, an error will be thrown and the token will be `null`.

However, you can call the `Pushy.isPermissionGranted()` method on Android to check whether the user has consented to receiving notifications or not. On iOS, since an error will be thrown, you can handle it accordingly in the `catch(error){ }` block.

On Flutter:
```
Future pushyRegister() async {
    try {
        // Register the user for push notifications (and display permission dialog)
        String deviceToken = await Pushy.register();

        // Print token to console/logcat
        print('Device token: $deviceToken');
    } catch (error) {
        // iOS: User denied push permission
        showDialog(
        context: context,
        builder: (BuildContext context) {
            return AlertDialog(
                title: Text('Error'),
                content: Text(error.toString()),
                actions: [ FlatButton( child: Text('OK'), onPressed: () { Navigator.of(context, rootNavigator: true).pop('dialog'); } )]
            );
        }
        );
    }
}
```

There is currently no way to receive a device token on iOS without the user consenting to receiving notifications. This is an Apple/APNS platform limitation.

We recommend allowing the user to log in without a device token, and then implementing an additional backend request to update the user's Pushy device token after they have logged in and consented to the dialog.

Please let us know if there's anything else we can help with.
