### ISSUE TITLE
Keychain conflict

### ISSUE THREAD

**Issue by leethree** [pushy/pushy-sdk-ios#3]
Pushy saves token in the iOS Keychain with `service`= bundle ID. but it could be used by other libraries and it will cause conflicts. 

For example, [`react-native-keychain`](https://github.com/oblador/react-native-keychain) stores generic password at the same location and it might clear Pushy's token when it resets.

You can see here pushy token is saved along side other app data.

<img width="693" alt="Screenshot_2020-04-08_at_12_43_05" src="https://user-images.githubusercontent.com/648142/78782540-186de080-799a-11ea-9a8e-983bb6351021.png">

The fix would be to save the token in a more specific `service` in KeyChain and/or allow users to specify where to store the tokens.

**Comment by pushy** [comment]
Hi @leethree,
Thanks for your report and concern about the Pushy keychain values being cleared.

It appears that the `react-native-keychain` method `resetGenericPassword()` clears only those keychain values which are used to store the credentials, and not other keychain values from other sources:
https://github.com/oblador/react-native-keychain/blob/7bd2e23bc53b6101ef12d6c073c1a85db5204865/android/src/main/java/com/oblador/keychain/KeychainModule.java#L324-L350

If we would change the `service=bundleID` configuration now, it would mean that apps updating to the new version of our iOS SDK would lose token persistence of existing users' devices using the old version.

Since we are not aware of any plugin that is currently clearing Pushy's keychain values, we can deem this as a non-issue for now.

**Comment by leethree** [comment]
The code you linked is for Android. In their iOS code, all the keys in the `service` are cleared:

https://github.com/oblador/react-native-keychain/blob/c6f276d19a73f9cfe0f9f497c9a4cc0d74b8f3bd/RNKeychainManager/RNKeychainManager.m#L239-L249

**Comment by pushy** [comment]
@leethree Thanks for the clarification.

Unfortunately, if we would change the `service=bundleID` setup now, it would mean that apps updating to the new version of our iOS SDK would lose token persistence of existing users' devices using the old version.

What we suggest instead is editing the `PushySDK/PushyKeychain.swift` file in your own project to work around this issue:
https://github.com/pushy-me/pushy-sdk-ios/blob/d58887f0164b80df05e0ee6bc67b37b7b04a5fbd/PushySDK/PushyKeychain.swift#L399

Please let us know if this is an acceptable solution.

**Comment by leethree** [comment]
fair enough. I'll try the workaround
