### ISSUE TITLE
Reset device token

### ISSUE THREAD

**Issue by hiteshborse12** [pushy/pushy-sdk-ios#5]
Uninstall and install a new app on same device getting old user notification.  Is there any way to every time generate a new token for new installation on the device.

**Comment by pushy** [comment]
Hi @hiteshborse12,
We'd be glad to assist with your inquiry.

Our recommended approach for avoiding this issue is as follows:

When a user logs out, always clear their associated Pushy device token from your backend database. Whenever any user logs in, send their most up-to-date device token to your backend for storage. In addition, before storing this device token, check whether any other users in your database have this Pushy device token assigned to them. If so, clear it from the other users first. Then, associate this Pushy device token only for the user currently logging in.
