### ISSUE TITLE
.background might be not the right QoS level for socket connection check

### ISSUE THREAD

**Issue by nikolaykasyanov** [pushy/pushy-sdk-ios#6]
According to the [table](https://developer.apple.com/library/archive/documentation/Performance/Conceptual/EnergyGuide-iOS/PrioritizeWorkWithQoS.html), it's either user initiated or utility, unless I'm missing something, because it's time sensitive and wouldn't like I/O throttling which is the case with background QoS as far as I'm aware.

https://github.com/pushy-me/pushy-sdk-ios/blob/86431348c00f23ff32258431c44cec4e3eed8ea6/PushySDK/PushyAPNs.swift#L32

**Comment by pushy** [comment]
Hi @nikolaykasyanov,
Thanks so much for bringing this to our attention.

Indeed, `.userInitiated` seems to be the best choice for avoiding throttling. This has been fixed in https://github.com/pushy-me/pushy-sdk-ios/commit/45bc074aedb8ebc0e1a60a8a928e00206ddb4713. Please let us know if you have anything to discuss further.

**Comment by nikolaykasyanov** [comment]
@pushy-me thanks for the quick reaction!
