### ISSUE TITLE
Not granting notification permissions shouldn't prevent receiving an APNS (and, consequently, a Pushy) token

### ISSUE THREAD

**Issue by nikolaykasyanov** [pushy/pushy-sdk-ios#7]
Hi, we've encountered this issue with the SDK.

For example, silent push notifications do not require a permission, at all, so it's totally legit to call `UIApplication.registerForRemoteNotifications` regardless of the notification authorization state.

No word about permissions [here](https://developer.apple.com/documentation/usernotifications/registering_your_app_with_apns) either.

**Comment by nikolaykasyanov** [comment]
Also this piece of code checks notification permissions: https://github.com/pushy-me/pushy-sdk-ios/blob/ed166bba00cf927d77f1b2153894c369ed912edd/PushySDK/Pushy.swift#L94.

I'd be very thankful for any workaround or fix for this behaviour.

**Comment by pushy** [comment]
Hi @nikolaykasyanov,
Thanks for your inquiry. We'd be glad to assist.

Whether documented by Apple or not, continuing to call `UIApplication.registerForRemoteNotifications()` after the user declines the push dialog results in APNs not assigning a device token for the device (`AppDelegate.didRegisterForRemoteNotificationsWithDeviceToken` callback not invoked), until you manually go into the settings and enable notifications for your app.

You can test this out yourself by cloning this repository and commenting out the two instances of code that invoke the error `PUSH_PERMISSION_DENIED` followed by a `return` statement.

Apologies for the inconvenience, but it appears that even for silent notifications, the push permission dialog must not be declined by the user.

Please let us know if there's anything else we can help with.

**Comment by nikolaykasyanov** [comment]
@pushy-me thanks for the update and sorry for the not very polite bug report. 

Thanks for the info!

Although, confusingly, I was able to fix the issue we were experiencing exactly by commenting the code that checks permissions, and I checked that `UIApplicationDelegate` callback is indeed invoked with an APNS token in this case, both before and after declining notification permissions after a fresh install.

Would it make sense to double check on your side?

**Comment by pushy** [comment]
Hi @nikolaykasyanov,
Sure thing. We've double checked and noticed that an APNs device token will only be assigned in case the push permission dialog was previously granted after the fresh install, and later notifications have been disabled.

In detail: After fresh installing your app, you consent to receiving notifications, and an APNs / Pushy token is assigned. However, if you later go into the settings and disable notifications for your app, Apple will still invoke the `didRegisterForRemoteNotificationsWithDeviceToken` with an APNs device token. 

But from our testing (on an iOS 14 device), the callback was never invoked when the dialog is declined after a fresh install. Interestingly enough, nor is the `didFailToRegisterForRemoteNotificationsWithError` callback invoked either.

What iOS version are you testing on?

**Comment by nikolaykasyanov** [comment]
I was testing on an iOS 14.4.2 device previously, recently I've been also testing on iOS 14.5 RC.

What I do:
- remove the app
- install and run it (without debugger attached)

I tried to arrange the calls to `registerForRemoteNotifications` and `requestAuthorization` differently, to verify when notification permission is declined before `registerForRemoteNotifications` and after it (in this case I also additionally check what happens after restarting the app).

I'm able to get an APNS token in both cases.

>But from our testing (on an iOS 14 device), the callback was never invoked when the dialog is declined after a fresh install. Interestingly enough, nor is the didFailToRegisterForRemoteNotificationsWithError callback invoked either.

Interesting, from my experience not getting any callsback called might have something to do with connection, i.e. when VPN goes into a weird state, but that probably doesn't apply here.

**Comment by pushy** [comment]
Hi @nikolaykasyanov,
Thanks for your persistence and for providing further information. We have been able to isolate the issue and provide a fix/workaround in https://github.com/pushy-me/pushy-sdk-ios/commit/fdab7b317764ec0e9380d3b7ba1d9affbc0f832f. 

The project we were testing on did not have the **Remote Notifications** background mode capability enabled in the Xcode project settings. This capability isn't needed for standard APNs notifications, but is of course needed for those Silent Notifications you are trying to send.

Indeed, with this capability enabled, an APNs token is assigned to the device, and a Pushy token should be assigned accordingly. Since there is no way to actively check at runtime whether the Remote Notifications background capability has been enabled in the project's App Entitlements, we've added a method that allows you to override the default behavior of erroring out when users decline the push permission dialog, or when the notification permission is later disabled in the iOS Settings for your app.

To use this new overriding functionality:

1) Please update your `Podfile` to reference version `1.0.32` of the [Pushy iOS SDK](https://pushy.me/docs/ios/get-sdk):

```
pod 'Pushy', '1.0.32'
```

2) Save the file and run the following command to update the SDK:

```
pod install
```

3) Add the following line of code before `pushy.register()`: 

```
// Enable support for silent/foreground notifications without push permission consent
pushy.toggleIgnorePushPermissionDenial(true)
```

4) Please run your app and confirm it is able to receive a Pushy device token even when the user denies the permission dialog.

Thanks again for your help with reporting, investigation, and resolving this issue. 😄

**Comment by nikolaykasyanov** [comment]
@pushy-me hey, thanks for the insight and the fix! 🚀
