### ISSUE TITLE
Silent Push notifications not receiving in iOS 14

### ISSUE THREAD

**Issue by chirag225** [pushy/pushy-sdk-ios#8]
Silent Push notifications not receiving in iOS 14
is There any changes for that

**Comment by pushy** [comment]
Hi @chirag225,
Thanks for reaching out. We'd be glad to assist with your inquiry.

Please be advised that due to Apple platform restrictions, silent notifications will **not** be delivered to your app if it has been swiped away from the recent apps / killed by the user. If you'd like notifications to be received in this scenario, please consider sending regular (non-silent) iOS notifications, without the `content_available: true` flag.

Please let me know if there's anything else we can help with.

**Comment by pushy** [comment]
Closing the issue due to lack of response, feel free to reply if you still need help with this.
